project:
  type: website
  output-dir: docs

# Meta
description-meta: "Haley Grant | Biostatistics and Health Data Science"
author-meta: "Haley Grant"

website:
  title: "Haley Grant"
  description: "Haley Grant | Biostatistics and Health Data Science"

  navbar:
    background: light

    left:
      - text: About
        href: index.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Teaching Resources
        href: resources.qmd
      - text: Publications
        href: publications.qmd
      - text: Students & Mentoring
        href: people.qmd
      - text: Contact
        href: contact.qmd

    right:
      - text: CV
        href: files/Grant_CV2026.pdf
      - icon: github
        href: https://github.com/haleykgrant/haleykgrant.github.io
        target: _blank

  page-navigation: true

  page-footer:
    left: "Haley Grant"
    right:
      - icon: github
        href: https://github.com/haleykgrant/haleykgrant.github.io
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true


  repo-url: https://github.com/haleykgrant/haleykgrant.github.io

  open-graph: true

  twitter-card: true

  site-url: "https://haleykgrant.github.io"

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript

